dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

before_script:
  - cd backend
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test