dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements-build.txt
before_script:
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
after_success:
  - bash test.sh
  
