# Generated by Django 2.2 on 2019-04-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='map_id',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='map_level_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.MapLevel'),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='map_level_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.MapLevel'),
        ),
        migrations.AlterField(
            model_name='block',
            name='map_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Map'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Task'),
        ),
        migrations.AlterField(
            model_name='maplevel',
            name='block_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Block'),
        ),
        migrations.AlterField(
            model_name='maplevel',
            name='level_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programtests',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programtests',
            name='output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programtests',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.TaskType'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Task'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Task'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Task'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
