# Generated by Django 2.2 on 2019-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190405_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplevel',
            name='level_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='programtests',
            name='input',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='programtests',
            name='output',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name_type',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='theory',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='theory',
            name='video',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
