# Generated by Django 2.2 on 2019-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190405_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
